### ISSUE TITLE
Should we aggregate "/api" endpoints?

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/MLplayground#14]
Currently, each app has a separate `/api` endpoint mounted on its URL (`/lumisectionHistos1D/API`, `/lumisectionHistos2D/API`). 

Wouldn't it be clearer if all endpoints where under a common `/api/` part of the URL?

E.g.  (`/api/lumisectionHistos1D/`, `/api/lumisectionHistos2D/`).

**Comment by Abhit03** [comment]
Yes, since as you suggested we can list all the API endpoints on `/api/` url instead of remembering all the prefix words before the `API`
