### ISSUE TITLE
Create a Task model to aggregate sets of data used for training and testing models

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/MLplayground#21]
The `Task` will be a "container" which will group data so that it can be serialized and used by users for training and testing their models.

They should include:
- Possibly a `ManyToMany` relationship with:
  - 1D Lumisection Histograms and/or
  - 2D Lumisection Histograms and/or
  - Run Histogams

The main point to keep in mind is that a `Task` should contain multiple histograms, and many histograms can belong to many different `Task`s

@Abhit03 @XavierAtCERN please verify that a `Task` should either aggregate a single type of histograms or a mix of them

**Comment by Abhit03** [comment]
Makes sense to me 
Since as you mentioned - We will have a table which will point to the foreign keys of `Task` and `Lumisection Histo`

**Comment by nothingface0** [comment]
From @XavierAtCERN:

>  what would be good for the front end would be to have a /create view with the three options I mentioned:

> - train on first lumisections of a run, test on the following
>   - Form with run number and start / stop lumisection for train + start / stop lumisection for test 
> - train on a few runs, test on the following
>   - Form with run numbers to train on and run number(s) to test
> - user defined train/test split
>   - Drag and drop area for a two column file (runs+lumisections) for train and one for test
